### ISSUE TITLE
Stale Repo?

### ISSUE THREAD

**Issue by longstone** [jaroslawhartman/withings-sync#57]
I see activity all over here - but not from the owner. 
Is there a fork that is up to date and merging all the PR?

Would be great to have this tool running on docker and with all the improvements running!

cheers!

**Comment by longstone** [comment]
In the meantime I've created another fork and merged most of the open PR's there. See https://github.com/longstone/withings-sync (even docker pull ghcr.io/longstone/withings-sync) is working.

Im now able to see my values from withings in garmin (even its only weight and body fat :)).

Hope that helps

**Comment by JoGu01** [comment]
I contacted Jarek over his homepage.
PRs should be merged now.
Since he is short on time, he offered to add someone as a maintainer for this repo.
Since my time (and knowledge) is also very limited, it would be nice if suitable volunteers would contact him. I think he would be happy about help.
His email address can be found on his homepage.

**Comment by jaroslawhartman** [comment]
Hi guys, sorry for lack of feedback from my side.

Mr @longstone has now been added as another maintainer of the repo. I hope he will help to process the backlog.

Many thanks and best regards,
Jarek
